apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: zack.brady@ranchergovernment.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher-ingress
  namespace: cattle-system
spec:
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: tls-rancher-certs
  dnsNames:
  - rancher.rancherfederal.training
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-longhorn-certs
  namespace: longhorn-system
spec:
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: tls-longhorn-certs
  dnsNames:
  - longhorn.rancherfederal.training
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-neuvector-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-neuvector-certs
  namespace: cattle-neuvector-system
spec:
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: tls-neuvector-certs
  dnsNames:
  - neuvector.rancherfederal.training